services:
  - type: web
    name: wavey-ceviches-rails
    env: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "1"
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_MASTER_KEY
        sync: false
